version: "3"

services:
  simple-scaffold:
    image: gradle:7.5.1-jdk17
    working_dir: /app
    container_name: simple-scaffold
    ports:
      - "8899:8080"
      - "5055:5005"
    volumes:
      - .:/app
    networks:
      - simple_network
    environment:
      DB_HOST: mysql-local
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
    command: gradle bootRun
    depends_on:
      - mysql-local

  mysql-local:
    image: mysql:8.0.31
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - simple_network
    volumes:
      - ~/MyStorage/db_volume:/var/lib/mysql:rw
    user: mysql
    ports:
      - "3306:3306"

networks:
  simple_network: